#version 450

#extension GL_ARB_separate_shader_objects : enable

struct Particle
{
    vec2 pos;
    vec2 vel;
};

// Binding 0 : Position storage buffer
layout(std140, binding = 0) buffer Pos
{
   Particle particles[ ];
};

layout (local_size_x = 256) in;

layout (binding = 1) uniform UBO
{
    float deltaT;
    int particleCount;
} ubo;

void main()
{
    // Current SSBO index
    uint index = gl_GlobalInvocationID.x;
    // Don't try to write beyond particle count
    if (index >= ubo.particleCount)
        return;

    // Read position and velocity
    vec2 vVel = particles[index].vel.xy;
    vec2 vPos = particles[index].pos.xy;

    // Move by velocity
    vPos += vVel * ubo.deltaT;

    particles[index].pos.xy = vPos;
    particles[index].vel.xy = vVel;
}
