#version 450
#extension GL_ARB_separate_shader_objects : enable

layout (local_size_x_id = 1, local_size_y_id = 2) in;

layout(push_constant) uniform PushConsts
{
    int width;
    int height;
    int red;
} consts;

layout(std430, binding = 0) buffer Pos
{
    float value[];
}x;

void main()
{
  ivec2 pos = ivec2(gl_GlobalInvocationID.xy);

  if (2 * pos.x < consts.width && pos.y < consts.height)
  {
    int offset = (pos.y & 1) ^ consts.red;
    int index = pos.y * consts.width + 2 * pos.x + offset;

    x.value[index] = 1;
  }
}
