#version 450

#extension GL_ARB_separate_shader_objects : enable

layout(std430, binding = 0) buffer Pos
{
   float numbers[];
}pos;

layout (local_size_x = 32, local_size_y = 32) in;

layout(push_constant) uniform PushConsts
{
	int width;
  int height;
} consts;

void main()
{
  uvec2 index = gl_GlobalInvocationID.xy;
  if (index.x < consts.width && index.y < consts.height)
  {
    if ((index.x + index.y) % 2 == 0)
    {
      pos.numbers[index.x + index.y * consts.width] = 1;
    }
    else
    {
      pos.numbers[index.x + index.y * consts.width] = 0;
    }
  }
}
