#version 450

#extension GL_ARB_separate_shader_objects : enable

layout(std430, binding = 0) buffer Pos
{
    float numbers[];
}pos;

layout (local_size_x_id = 1, local_size_y_id = 2) in;
layout (constant_id = 3) const int value = 0;

layout(push_constant) uniform PushConsts
{
    int width;
    int height;
} consts;

void main()
{
  uvec2 localSize = gl_WorkGroupSize.xy; // hack for Mali-GPU

  uvec2 index = gl_GlobalInvocationID.xy;
  if (index.x < consts.width && index.y < consts.height)
  {
    if ((index.x + index.y) % 2 == 0)
    {
      pos.numbers[index.x + index.y * consts.width] = value;
    }
    else
    {
      pos.numbers[index.x + index.y * consts.width] = 0;
    }
  }
}
