name: Build Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_ubuntu_x11:
    name: Build Ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Vulkan SDK
        id  : cache-vulkan-sdk
        uses: actions/cache@v1
        with:
          path: "1.3.204.1"
          key: vulkan-sdk-1.3.204.1

      - name: Setup Vulkan
        if: steps.cache-vulkan-sdk.outputs.cache-hit != 'true'
        run: |
          wget https://sdk.lunarg.com/sdk/download/1.3.204.1/linux/vulkansdk-linux-x86_64-1.3.204.1.tar.gz?Human=true -O vulkansdk-linux-x86_64-1.3.204.1.tar.gz
          tar -xf vulkansdk-linux-x86_64-1.3.204.1.tar.gz

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev mesa-common-dev

      - name: Build
        run: |
          export VULKAN_SDK=`pwd`/1.3.204.1/x86_64
          cmake . -DVORTEX3D_ENABLE_TESTS=On -DVORTEX3D_ENABLE_EXAMPLES=On
          make -j 2
  build_windows:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.1.1
        with:
          version: 1.3.204.0
          cache: true

      - name: Build
        run: |
          set VULKAN_SDK="%CD%\VulkanSDK"
          echo %VULKAN_SDK%
          mkdir build && cd build
          cmake .. -DVORTEX3D_ENABLE_TESTS=On -DVORTEX3D_ENABLE_EXAMPLES=On
          cmake --build . -j 2

  # build_macos:
  #   name: Build macOS
  #   runs-on: macos-latest

  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: Cache Vulkan SDK
  #     id: cache-vulkan-sdk
  #     uses: actions/cache@v1
  #     with:
  #       path: "vulkansdk-macos-1.3.204.1"
  #       key: vulkansdk-macos-1.3.204.1

  #   - name: Setup Vulkan
  #     if: steps.cache-vulkan-sdk.outputs.cache-hit != 'true'
  #     run: |
  #       wget https://sdk.lunarg.com/sdk/download/1.3.204.1/mac/vulkansdk-macos-1.3.204.1.dmg?Human=true -O vulkansdk-macos-1.3.204.1.dmg
  #       hdiutil attach vulkansdk-macos-1.3.204.1.dmg
  #       cp -r /Volumes/vulkansdk-macos-1.3.204.1 .
  #       hdiutil detach /Volumes/vulkansdk-macos-1.3.204.1

  #   - name: Build x86_64
  #     run: |
  #       export VULKAN_SDK=`pwd`/vulkansdk-macos-1.3.204.1/macOS
  #       mkdir build && cd build
  #       cmake .. -DMOLTENVK_DIR=`pwd`/../vulkansdk-macos-1.3.204.1/MoltenVK -DGLSL_VALIDATOR=`pwd`/../vulkansdk-macos-1.3.204.1/macOS/bin/glslangValidator -DVORTEX3D_ENABLE_TESTS=On -DVORTEX3D_ENABLE_EXAMPLES=On -DCMAKE_CXX_FLAGS="-Wno-documentation-unknown-command"
  #       cmake --build . -j 2
